import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const sfxDir = join(root, "assets", "sfx");

const files = {
  GUN_PISTOL_B64: "gun_pistol.wav",
  GUN_SHOTGUN_B64: "gun_shotgun.wav",
  GUN_RIFLE_B64: "gun_rifle.wav",
};

const lines = [
  "// Auto-generated by scripts/embed-sfx.mjs — do not edit by hand.",
  "",
];

for (const [name, file] of Object.entries(files)) {
  const b64 = readFileSync(join(sfxDir, file)).toString("base64");
  lines.push(`export const ${name} = ${JSON.stringify(b64)};`);
  lines.push("");
}

writeFileSync(join(root, "src", "sfx-buffers.js"), lines.join("\n"), "utf8");
console.log("Embedded SFX buffers into src/sfx-buffers.js");
